"""
DOCX Exports — generate Word documents for bid pack deliverables.

Three generators:
    1. generate_rfis_docx          — RFI log table
    2. generate_exclusions_docx    — exclusions + clarifications
    3. generate_bid_summary_docx   — full bid summary mirror

All return bytes (io.BytesIO) for Streamlit download.
Pure functions, no Streamlit dependency.
"""

import io
from datetime import datetime
from typing import Any, Dict, List, Optional

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH


# =============================================================================
# HELPERS
# =============================================================================

def _safe_str(val: Any, max_len: int = 120) -> str:
    """Safely convert to string and truncate."""
    s = str(val) if val is not None else ""
    if len(s) > max_len:
        s = s[:max_len] + "..."
    return s


def _add_heading(doc: Document, text: str, level: int = 1):
    """Add a heading with consistent styling."""
    doc.add_heading(text, level=level)


def _add_table(doc: Document, headers: List[str], rows: List[List[str]]):
    """Add a formatted table with headers and data rows."""
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Light List Accent 1'
    table.alignment = WD_TABLE_ALIGNMENT.LEFT

    # Header row
    hdr_cells = table.rows[0].cells
    for i, h in enumerate(headers):
        hdr_cells[i].text = h

    # Data rows
    for r_idx, row in enumerate(rows):
        cells = table.rows[r_idx + 1].cells
        for c_idx, val in enumerate(row):
            cells[c_idx].text = str(val)

    return table


# =============================================================================
# 1. RFIs DOCX
# =============================================================================

def generate_rfis_docx(
    rfis: List[dict],
    project_id: str = "",
    include_drafts: bool = False,
) -> bytes:
    """
    Generate an RFI log as a DOCX document.

    Args:
        rfis: List of RFI dicts {question, trade, priority, source_page, resolution}.
        project_id: Project identifier for header.
        include_drafts: If False, only approved/sent RFIs are included.

    Returns:
        DOCX content as bytes.
    """
    # Sprint 13: Filter by approval state
    from src.analysis.approval_states import filter_rfis_for_export
    rfis = filter_rfis_for_export(rfis, include_drafts=include_drafts)

    doc = Document()

    # Title
    title = doc.add_heading(f"RFI Log — {project_id or 'Project'}", level=0)
    doc.add_paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | "
        f"Total RFIs: {len(rfis)}"
    )
    doc.add_paragraph("")

    if not rfis:
        doc.add_paragraph("No RFIs generated.")
    else:
        # Build table
        headers = ["#", "Trade", "Priority", "Question", "Resolution"]
        rows = []
        for i, rfi in enumerate(rfis, 1):
            rows.append([
                str(i),
                _safe_str(rfi.get("trade", ""), 20).title(),
                _safe_str(rfi.get("priority", ""), 10).upper(),
                _safe_str(rfi.get("question", ""), 100),
                _safe_str(rfi.get("resolution", "Open"), 40),
            ])
        _add_table(doc, headers, rows)

    # Footer
    doc.add_paragraph("")
    footer_para = doc.add_paragraph("Generated by xBOQ Bid Engineer")
    footer_para.runs[0].font.size = Pt(8)
    footer_para.runs[0].font.color.rgb = RGBColor(0x71, 0x80, 0x96)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# =============================================================================
# 2. EXCLUSIONS & CLARIFICATIONS DOCX
# =============================================================================

def generate_exclusions_docx(
    assumptions: Optional[List[dict]] = None,
    pricing_guidance: Optional[dict] = None,
    project_id: str = "",
) -> bytes:
    """
    Generate an Exclusions & Clarifications DOCX document.

    Combines:
        - Rejected assumptions → Exclusions
        - Accepted assumptions → Clarifications
        - Pricing guidance recommended exclusions/clarifications

    Args:
        assumptions: List of assumption dicts with status field.
        pricing_guidance: Pricing guidance dict from compute_pricing_guidance().
        project_id: Project identifier for header.

    Returns:
        DOCX content as bytes.
    """
    doc = Document()

    # Title
    doc.add_heading(
        f"Exclusions & Clarifications — {project_id or 'Project'}", level=0,
    )
    doc.add_paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    )
    doc.add_paragraph("")

    assumptions = assumptions or []
    rejected = [a for a in assumptions if a.get("status") == "rejected"]
    accepted = [a for a in assumptions if a.get("status") == "accepted"]

    # Section 1: Exclusions from assumptions
    doc.add_heading("Exclusions", level=1)
    if rejected:
        for a in rejected:
            title = _safe_str(a.get("title", ""), 120)
            cost = a.get("cost_impact")
            cost_str = f" [Cost impact: {cost}]" if cost is not None else ""
            p = doc.add_paragraph(style='List Bullet')
            run = p.add_run(f"{title}{cost_str}")
    else:
        doc.add_paragraph("No exclusions from assumption review.")

    # Pricing guidance exclusions
    pg_excl = (pricing_guidance or {}).get("recommended_exclusions", [])
    if pg_excl:
        doc.add_heading("Additional Recommended Exclusions (from analysis)", level=2)
        for e in pg_excl:
            doc.add_paragraph(_safe_str(e, 150), style='List Bullet')

    doc.add_paragraph("")

    # Section 2: Clarifications from assumptions
    doc.add_heading("Clarifications", level=1)
    if accepted:
        for a in accepted:
            title = _safe_str(a.get("title", ""), 120)
            cost = a.get("cost_impact")
            cost_str = f" [Cost impact: {cost}]" if cost is not None else ""
            p = doc.add_paragraph(style='List Bullet')
            run = p.add_run(f"{title}{cost_str}")
    else:
        doc.add_paragraph("No clarifications from assumption review.")

    # Pricing guidance clarifications
    pg_clar = (pricing_guidance or {}).get("recommended_clarifications", [])
    if pg_clar:
        doc.add_heading("Additional Recommended Clarifications (from analysis)", level=2)
        for c in pg_clar:
            doc.add_paragraph(_safe_str(c, 150), style='List Bullet')

    # Footer
    doc.add_paragraph("")
    footer_para = doc.add_paragraph("Generated by xBOQ Bid Engineer")
    footer_para.runs[0].font.size = Pt(8)
    footer_para.runs[0].font.color.rgb = RGBColor(0x71, 0x80, 0x96)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# =============================================================================
# 3. BID SUMMARY DOCX
# =============================================================================

def generate_bid_summary_docx(
    payload: Dict[str, Any],
    bid_strategy: Optional[Dict[str, Any]] = None,
    assumptions: Optional[List[Dict[str, Any]]] = None,
    include_drafts: bool = False,
    collaboration_entries: Optional[List[dict]] = None,
) -> bytes:
    """
    Generate a bid summary as a DOCX document — mirrors bid_summary.py sections.

    Args:
        payload: Full analysis payload dict.
        bid_strategy: Optional bid strategy dict.
        assumptions: Optional list of assumption dicts.
        include_drafts: If False, only approved/sent RFIs and reviewed conflicts are included.

    Returns:
        DOCX content as bytes.
    """
    # Sprint 13: Filter payload items by approval state
    from src.analysis.approval_states import filter_rfis_for_export, filter_conflicts_for_export
    payload = dict(payload)  # shallow copy to avoid mutating original
    payload["rfis"] = filter_rfis_for_export(payload.get("rfis", []), include_drafts=include_drafts)
    payload["conflicts"] = filter_conflicts_for_export(payload.get("conflicts", []), include_unreviewed=include_drafts)

    doc = Document()

    project_id = payload.get("project_id", "Unknown")
    timestamp = payload.get("timestamp", datetime.now().isoformat())

    # Title
    doc.add_heading(f"Bid Summary: {project_id}", level=0)
    doc.add_paragraph(f"Generated: {timestamp}")
    doc.add_paragraph("")

    readiness = payload.get("readiness_score", 0)
    decision = payload.get("decision", "N/A")
    doc.add_paragraph(f"Readiness Score: {readiness}/100 | Decision: {decision}")
    doc.add_paragraph("")

    # ── Document Coverage ──────────────────────────────────────────
    overview = payload.get("drawing_overview") or {}
    doc.add_heading("Document Coverage", level=1)
    files = overview.get("files", ["N/A"])
    doc.add_paragraph(f"Files: {', '.join(_safe_str(f, 60) for f in files[:5])}")
    doc.add_paragraph(f"Total Pages: {overview.get('pages_total', 0)}")
    disciplines = overview.get("disciplines_detected", [])
    if disciplines:
        doc.add_paragraph(f"Disciplines: {', '.join(disciplines)}")

    # ── Extracted Items ────────────────────────────────────────────
    ext = payload.get("extraction_summary", {})
    counts = ext.get("counts", {})
    if counts:
        doc.add_heading("Extracted Items", level=1)
        headers = ["Category", "Count"]
        rows = [[k.replace("_", " ").title(), str(v)] for k, v in counts.items()]
        _add_table(doc, headers, rows)

    # ── Top RFIs ───────────────────────────────────────────────────
    rfis = payload.get("rfis", [])
    if rfis:
        doc.add_heading(f"Top RFIs ({len(rfis)} total)", level=1)
        headers = ["#", "Trade", "Priority", "Question"]
        rows = []
        for i, rfi in enumerate(rfis[:15], 1):
            rows.append([
                str(i),
                _safe_str(rfi.get("trade", ""), 20).title(),
                _safe_str(rfi.get("priority", ""), 10).upper(),
                _safe_str(rfi.get("question", ""), 80),
            ])
        _add_table(doc, headers, rows)
        if len(rfis) > 15:
            doc.add_paragraph(f"...and {len(rfis) - 15} more")

    # ── Blockers ───────────────────────────────────────────────────
    blockers = payload.get("blockers", [])
    if blockers:
        doc.add_heading(f"Blockers ({len(blockers)})", level=1)
        for b in blockers[:10]:
            sev = (b.get("severity", "") or "").upper()
            title = _safe_str(b.get("title", ""), 100)
            trade = _safe_str(b.get("trade", ""), 20).title()
            doc.add_paragraph(f"[{sev}] {trade}: {title}", style='List Bullet')
        if len(blockers) > 10:
            doc.add_paragraph(f"...and {len(blockers) - 10} more")

    # ── Addenda ────────────────────────────────────────────────────
    addenda = payload.get("addendum_index", [])
    if addenda:
        doc.add_heading(f"Addenda ({len(addenda)})", level=1)
        for a in addenda:
            no = a.get("addendum_no", "?")
            date = a.get("date", "")
            title = _safe_str(a.get("title", "Untitled"), 80)
            date_str = f" ({date})" if date else ""
            doc.add_paragraph(f"Addendum {no}{date_str}: {title}", style='List Bullet')

    # ── Conflicts ──────────────────────────────────────────────────
    conflicts = payload.get("conflicts", [])
    if conflicts:
        doc.add_heading(f"Conflicts ({len(conflicts)})", level=1)
        for c in conflicts[:10]:
            ctype = c.get("type", "").replace("_", " ").title()
            if c.get("resolution") == "intentional_revision":
                ctype += " (Revision)"
            desc = c.get("description", "") or c.get("text", "") or str(c.get("item_no", ""))
            doc.add_paragraph(f"{ctype}: {_safe_str(desc, 100)}", style='List Bullet')
        if len(conflicts) > 10:
            doc.add_paragraph(f"...and {len(conflicts) - 10} more")

    # ── Exclusions & Clarifications ────────────────────────────────
    if assumptions:
        rejected = [a for a in assumptions if a.get("status") == "rejected"]
        accepted = [a for a in assumptions if a.get("status") == "accepted"]
        if rejected or accepted:
            doc.add_heading("Exclusions & Clarifications", level=1)
            if rejected:
                doc.add_heading("Exclusions", level=2)
                for a in rejected:
                    title = _safe_str(a.get("title", ""), 100)
                    doc.add_paragraph(title, style='List Bullet')
            if accepted:
                doc.add_heading("Clarifications", level=2)
                for a in accepted:
                    title = _safe_str(a.get("title", ""), 100)
                    doc.add_paragraph(title, style='List Bullet')

    # ── Bid Strategy ───────────────────────────────────────────────
    if bid_strategy:
        doc.add_heading("Bid Strategy Assessment", level=1)
        for key in ("client_fit", "risk_score", "competition_score", "readiness_score"):
            dial = bid_strategy.get(key, {})
            name = dial.get("name", key.replace("_", " ").title())
            score_val = dial.get("score")
            conf = dial.get("confidence", "")
            if score_val is not None:
                doc.add_paragraph(f"{name}: {score_val}/100 ({conf})", style='List Bullet')
            else:
                doc.add_paragraph(f"{name}: Not computed", style='List Bullet')
        recs = bid_strategy.get("recommendations", [])
        if recs:
            doc.add_heading("Recommendations", level=2)
            for r in recs:
                doc.add_paragraph(_safe_str(r, 120), style='List Bullet')

    # ── QA Score ───────────────────────────────────────────────────
    qa_score = payload.get("qa_score")
    if qa_score and isinstance(qa_score, dict):
        score_val = qa_score.get("score", 0)
        confidence = qa_score.get("confidence", "")
        doc.add_heading(f"Bid Pack QA Score: {score_val}/100 ({confidence})", level=1)

        breakdown = qa_score.get("breakdown", {})
        if breakdown:
            headers = ["Component", "Score"]
            rows = [
                [k.replace("_", " ").title(), f"{v}/20"]
                for k, v in breakdown.items()
            ]
            _add_table(doc, headers, rows)

        top_actions = qa_score.get("top_actions", [])
        if top_actions:
            doc.add_heading("Top Actions to Improve", level=2)
            for action in top_actions[:5]:
                doc.add_paragraph(_safe_str(action, 120), style='List Bullet')

    # ── Pricing Guidance ──────────────────────────────────────────
    pricing = payload.get("pricing_guidance")
    if pricing and isinstance(pricing, dict):
        doc.add_heading("Pricing Guidance", level=1)

        cont = pricing.get("contingency_range", {})
        if cont:
            doc.add_heading("Contingency Range", level=2)
            headers = ["Metric", "Value"]
            rows = [
                ["Low", f"{cont.get('low_pct', 0)}%"],
                ["High", f"{cont.get('high_pct', 0)}%"],
                ["Recommended", f"{cont.get('recommended_pct', 0)}%"],
            ]
            _add_table(doc, headers, rows)
            rationale = cont.get("rationale", "")
            if rationale:
                p = doc.add_paragraph(_safe_str(rationale, 200))
                p.runs[0].italic = True

        excl = pricing.get("recommended_exclusions", [])
        if excl:
            doc.add_heading("Recommended Exclusions", level=2)
            for e in excl:
                doc.add_paragraph(_safe_str(e, 150), style='List Bullet')

        clar = pricing.get("recommended_clarifications", [])
        if clar:
            doc.add_heading("Recommended Clarifications", level=2)
            for c in clar[:15]:
                doc.add_paragraph(_safe_str(c, 150), style='List Bullet')

        ve = pricing.get("suggested_alternates_ve", [])
        if ve:
            doc.add_heading("Suggested Alternates / Value Engineering", level=2)
            for v in ve:
                item = _safe_str(v.get("item", ""), 100)
                reason = _safe_str(v.get("reason", ""), 100)
                p = doc.add_paragraph(style='List Bullet')
                p.add_run(item).bold = True
                if reason:
                    p.add_run(f" — {reason}")

    # ── Estimating Playbook / Basis of Estimate (Sprint 20C) ────────
    _ep = payload.get("estimating_playbook")
    if _ep and isinstance(_ep, dict):
        try:
            from src.analysis.estimating_playbook import summarize_playbook_for_exports
            _ep_summary = summarize_playbook_for_exports(_ep)
            if _ep_summary:
                doc.add_heading("Basis of Estimate", level=1)
                for _ep_line in _ep_summary.split("\n"):
                    _ep_line = _ep_line.strip()
                    if not _ep_line:
                        continue
                    # Strip markdown bold markers for Word
                    _ep_clean = _ep_line.replace("**", "")
                    doc.add_paragraph(_ep_clean)

            # Basis of recommendation from pricing guidance
            _bor = (pricing or {}).get("basis_of_recommendation", [])
            if _bor:
                doc.add_heading("Contingency Basis", level=2)
                for _b in _bor:
                    doc.add_paragraph(_safe_str(_b, 150), style='List Bullet')
        except Exception:
            pass

    # ── Sprint 14: Collaboration Notes Appendix ─────────────────────
    if collaboration_entries:
        try:
            from src.analysis.collaboration import build_collaboration_appendix
            appendix_text = build_collaboration_appendix(collaboration_entries)
            if appendix_text:
                doc.add_page_break()
                doc.add_heading("Collaboration Notes", level=1)
                for _cl_line in appendix_text.split("\n"):
                    if _cl_line.startswith("===") or _cl_line.startswith("---"):
                        continue  # skip dividers
                    elif _cl_line.startswith("COLLABORATION"):
                        continue  # skip header (we used add_heading above)
                    elif _cl_line and not _cl_line.startswith(" "):
                        doc.add_heading(_cl_line, level=2)
                    elif _cl_line.strip():
                        doc.add_paragraph(_cl_line.strip())
        except Exception:
            pass

    # ── Footer ─────────────────────────────────────────────────────
    doc.add_paragraph("")
    footer_para = doc.add_paragraph("Generated by xBOQ Bid Engineer")
    footer_para.runs[0].font.size = Pt(8)
    footer_para.runs[0].font.color.rgb = RGBColor(0x71, 0x80, 0x96)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
