"""
Pilot Docs Generator — produces pilot agreement and supporting docs.

Three generators:
    1. generate_pilot_agreement_docx   — 1-page pilot agreement
    2. generate_data_handling_docx     — data handling options
    3. generate_pilot_checklist_docx   — pilot checklist

All return bytes (io.BytesIO) for Streamlit download.
Pure functions, no Streamlit dependency.

Sprint 20: Pilot Conversion + Paired Dataset Capture.
"""

import io
from datetime import datetime
from typing import Any, Dict

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


# ── Pilot Agreement ──────────────────────────────────────────────────────

def generate_pilot_agreement_docx(
    project_metadata: Dict[str, Any],
) -> bytes:
    """
    Generate a 1-page Pilot Agreement DOCX, pre-filled with project metadata.

    Args:
        project_metadata: Dict with name, owner, company_name, bid_date,
                          trades_in_scope, etc.

    Returns:
        DOCX content as bytes.
    """
    doc = Document()

    # Title
    title = doc.add_heading("Pilot Engagement Agreement", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(
        f"Date: {datetime.now().strftime('%Y-%m-%d')}"
    )
    doc.add_paragraph("")

    # Parties
    doc.add_heading("Parties", level=1)
    company = (
        project_metadata.get("company_name")
        or project_metadata.get("owner", "___________")
    )
    doc.add_paragraph(f"Client: {company}")
    doc.add_paragraph(
        f"Project: {project_metadata.get('name', '___________')}"
    )
    doc.add_paragraph("Provider: xBOQ (Pre-Construction Scope & Risk Tool)")
    doc.add_paragraph("")

    # Scope
    doc.add_heading("Pilot Scope", level=1)
    trades = project_metadata.get("trades_in_scope", [])
    trades_str = ", ".join(trades) if trades else "All trades in tender package"
    doc.add_paragraph(f"Trades in scope: {trades_str}")
    doc.add_paragraph(
        f"Bid due date: {project_metadata.get('bid_date', '___________')}"
    )
    doc.add_paragraph(
        "Deliverables: Automated scope check, RFI log, "
        "quantity takeoff, diff report vs estimate"
    )
    doc.add_paragraph("")

    # Terms
    doc.add_heading("Terms", level=1)
    terms = [
        "Pilot duration: scope of one (1) tender bid cycle.",
        "No cost to Client during pilot period.",
        "Client provides: tender documents (PDFs), estimate/takeoff for comparison.",
        "Provider delivers: analysis report, diff report, training data pack.",
        "Data handling: per attached Data Handling Options document.",
        "Either party may terminate with 7 days written notice.",
    ]
    for t in terms:
        doc.add_paragraph(t, style="List Number")

    doc.add_paragraph("")

    # Signatures
    doc.add_heading("Signatures", level=1)
    doc.add_paragraph(
        f"Client ({company}): ______________________  Date: __________"
    )
    doc.add_paragraph("")
    doc.add_paragraph(
        "xBOQ: ______________________  Date: __________"
    )

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph(
        "Generated by xBOQ — Sprint 20 Pilot Conversion"
    )
    for run in footer.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x71, 0x80, 0x96)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# ── Data Handling Options ────────────────────────────────────────────────

def generate_data_handling_docx(
    project_metadata: Dict[str, Any],
) -> bytes:
    """
    Generate a data handling options document.

    Describes three data retention tiers and how tender documents are handled.
    """
    doc = Document()
    doc.add_heading("Data Handling Options", level=0)

    company = (
        project_metadata.get("company_name")
        or project_metadata.get("owner", "Client")
    )
    doc.add_paragraph(
        f"Prepared for: {company} — "
        f"Project: {project_metadata.get('name', '—')}"
    )
    doc.add_paragraph("")

    doc.add_heading("Option A: No Retention", level=1)
    doc.add_paragraph(
        "All uploaded tender documents and analysis outputs are deleted "
        "within 24 hours of delivery. No data is retained for training. "
        "Suitable for highly confidential tenders."
    )

    doc.add_heading("Option B: 30-Day Retention", level=1)
    doc.add_paragraph(
        "Tender documents and outputs are retained for 30 days to allow "
        "re-runs, corrections, and follow-up analysis. After 30 days, "
        "all data is permanently deleted. No data is used for training."
    )

    doc.add_heading("Option C: Opt-In Training", level=1)
    doc.add_paragraph(
        "Client opts in to contribute anonymized data to improve xBOQ's "
        "extraction models. Tender documents are anonymized (project names, "
        "company names, amounts redacted) before inclusion in training sets. "
        "Client retains the right to withdraw consent at any time."
    )
    doc.add_paragraph("")

    doc.add_heading("Security Measures", level=1)
    measures = [
        "All data encrypted at rest (AES-256) and in transit (TLS 1.3).",
        "Access restricted to authorized personnel only.",
        "Audit trail maintained for all data access events.",
        "SOC 2 Type II compliance in progress.",
    ]
    for m in measures:
        doc.add_paragraph(m, style="List Bullet")

    doc.add_paragraph("")
    doc.add_paragraph(
        f"Selected option: ____________  "
        f"Authorized by ({company}): ____________  "
        f"Date: ____________"
    )

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


# ── Pilot Checklist ──────────────────────────────────────────────────────

def generate_pilot_checklist_docx(
    project_metadata: Dict[str, Any],
) -> bytes:
    """
    Generate a pilot readiness checklist.

    Pre-filled with project metadata, includes checkboxes for each step.
    """
    doc = Document()
    doc.add_heading("Pilot Readiness Checklist", level=0)

    company = (
        project_metadata.get("company_name")
        or project_metadata.get("owner", "Client")
    )
    doc.add_paragraph(
        f"Company: {company} | "
        f"Project: {project_metadata.get('name', '—')} | "
        f"Bid Date: {project_metadata.get('bid_date', '—')}"
    )
    doc.add_paragraph("")

    doc.add_heading("Pre-Pilot Setup", level=1)
    pre_items = [
        "Pilot Agreement signed by both parties",
        "Data Handling Option selected (A / B / C)",
        "Primary contact identified at client",
        "Tender documents (PDFs) collected",
    ]
    for item in pre_items:
        doc.add_paragraph(f"\u2610  {item}")

    doc.add_heading("Document Upload", level=1)
    upload_items = [
        "All tender drawing PDFs uploaded",
        "BOQ / Bill of Quantities uploaded (if available)",
        "Tender conditions / contract document uploaded",
        "Addenda / corrigenda uploaded (if any)",
    ]
    for item in upload_items:
        doc.add_paragraph(f"\u2610  {item}")

    doc.add_heading("Ground Truth (for accuracy comparison)", level=1)
    gt_items = [
        "Client's estimate / takeoff provided (Excel or PDF)",
        "Column mapping completed in xBOQ",
        "Trades in scope confirmed",
    ]
    for item in gt_items:
        doc.add_paragraph(f"\u2610  {item}")

    doc.add_heading("Analysis & Review", level=1)
    review_items = [
        "First analysis run completed",
        "Diff report reviewed with client",
        "RFI log reviewed and validated",
        "Feedback captured (correct / wrong / edited)",
        "Training pack exported",
    ]
    for item in review_items:
        doc.add_paragraph(f"\u2610  {item}")

    doc.add_paragraph("")
    doc.add_paragraph(
        f"Completed by: ____________  Date: ____________"
    )

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
