"""
Submission Pack Generator — build structured ZIP for tender submission.

Folder structure:
  /00_Cover_Sheet.txt
  /01_Bid_Summary/
  /02_RFIs/
  /03_Exclusions_Clarifications/
  /04_Quantities/
  /05_Evidence_Appendix/

Pure function, no Streamlit dependency.
"""

import io
import zipfile
from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List, Optional


# ─── Folder Mapping ──────────────────────────────────────────────────────

SUBMISSION_FOLDER_MAP = {
    # 01_Bid_Summary
    "bid_summary.pdf": ("01_Bid_Summary", "Bid_Summary.pdf"),
    "bid_summary.docx": ("01_Bid_Summary", "Bid_Summary.docx"),
    "bid_summary.md": ("01_Bid_Summary", "Bid_Summary.md"),

    # 02_RFIs
    "rfis.csv": ("02_RFIs", "RFI_Log.csv"),
    "rfis.docx": ("02_RFIs", "RFI_Log.docx"),
    "grouped_rfis.csv": ("02_RFIs", "Grouped_RFIs.csv"),

    # 03_Exclusions_Clarifications
    "exclusions_clarifications.txt": ("03_Exclusions_Clarifications", "Exclusions_Clarifications.txt"),
    "exclusions_clarifications.csv": ("03_Exclusions_Clarifications", "Exclusions_Clarifications.csv"),
    "exclusions_clarifications.docx": ("03_Exclusions_Clarifications", "Exclusions_Clarifications.docx"),
    "assumptions.csv": ("03_Exclusions_Clarifications", "Assumptions.csv"),
    "pricing_guidance.txt": ("03_Exclusions_Clarifications", "Pricing_Guidance.txt"),

    # 04_Quantities
    "boq.csv": ("04_Quantities", "BOQ.csv"),
    "quantities.csv": ("04_Quantities", "Quantities.csv"),
    "schedules.csv": ("04_Quantities", "Schedules.csv"),
    "quantity_reconciliation.csv": ("04_Quantities", "Quantity_Reconciliation.csv"),
    "finishes_takeoff.csv": ("04_Quantities", "Finishes_Takeoff.csv"),

    # 05_Evidence_Appendix
    "requirements.csv": ("05_Evidence_Appendix", "Requirements.csv"),
    "feedback.jsonl": ("05_Evidence_Appendix", "Feedback.jsonl"),
    "evidence_appendix.pdf": ("05_Evidence_Appendix", "Evidence_Appendix.pdf"),

    # Sprint 15: Email drafts
    "rfi_email_all.txt": ("02_RFIs", "RFI_Email_Draft.txt"),
    "exclusions_email.txt": ("03_Exclusions_Clarifications", "Exclusions_Email_Draft.txt"),
}

# Fallback folder for unmapped files
_FALLBACK_FOLDER = "05_Evidence_Appendix"


# ─── Manifest Preview ────────────────────────────────────────────────────

def get_submission_manifest(csv_buffers: Dict[str, Any]) -> Dict[str, List[str]]:
    """
    Preview which files will go where.

    Args:
        csv_buffers: Dict mapping filename → str|bytes from the export section.

    Returns:
        Dict of {folder_name: [filename, ...]} sorted by folder name.
    """
    manifest: Dict[str, List[str]] = defaultdict(list)

    for source_name in csv_buffers:
        if source_name in SUBMISSION_FOLDER_MAP:
            folder, dest_name = SUBMISSION_FOLDER_MAP[source_name]
        elif source_name.startswith("rfi_email_"):
            # Sprint 15: Per-trade RFI email drafts → 02_RFIs/
            folder = "02_RFIs"
            dest_name = source_name.replace("rfi_email_", "RFI_Email_").replace(".txt", ".txt")
        else:
            folder = _FALLBACK_FOLDER
            dest_name = source_name
        manifest[folder].append(dest_name)

    # Sort files within each folder
    for folder in manifest:
        manifest[folder].sort()

    return dict(sorted(manifest.items()))


# ─── Cover Sheet ──────────────────────────────────────────────────────────

def _build_cover_sheet(
    project_id: str,
    project_name: str,
    manifest: Dict[str, List[str]],
) -> str:
    """Build a plain text cover sheet listing all included files."""
    lines = [
        "SUBMISSION PACK",
        "=" * 50,
        "",
        f"Project: {project_name or project_id or 'N/A'}",
        f"Project ID: {project_id or 'N/A'}",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "CONTENTS",
        "-" * 50,
    ]

    total_files = 0
    for folder in sorted(manifest.keys()):
        files = manifest[folder]
        lines.append(f"\n{folder}/")
        for fname in files:
            lines.append(f"  - {fname}")
            total_files += 1

    lines.extend([
        "",
        "-" * 50,
        f"Total files: {total_files}",
        "",
        "Generated by xBOQ Pre-Construction Scope Tool",
    ])

    return "\n".join(lines)


# ─── Main Generator ──────────────────────────────────────────────────────

def generate_submission_pack(
    csv_buffers: Dict[str, Any],
    project_id: str = "",
    project_name: str = "",
    collaboration_appendix: str = "",
) -> bytes:
    """
    Generate a structured submission pack ZIP from csv_buffers dict.

    Args:
        csv_buffers: Dict mapping filename → str|bytes (from demo_page export section).
        project_id: Project identifier for cover sheet.
        project_name: Human-readable project name.
        collaboration_appendix: Optional text appendix of comments/assignments.

    Returns:
        ZIP file content as bytes.
    """
    manifest = get_submission_manifest(csv_buffers)
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Write cover sheet at root
        cover = _build_cover_sheet(project_id, project_name, manifest)
        zf.writestr("00_Cover_Sheet.txt", cover)

        # Write each file into its mapped folder
        for source_name, content in csv_buffers.items():
            if source_name in SUBMISSION_FOLDER_MAP:
                folder, dest_name = SUBMISSION_FOLDER_MAP[source_name]
            elif source_name.startswith("rfi_email_"):
                # Sprint 15: Per-trade RFI email drafts → 02_RFIs/
                folder = "02_RFIs"
                dest_name = source_name.replace("rfi_email_", "RFI_Email_").replace(".txt", ".txt")
            else:
                folder = _FALLBACK_FOLDER
                dest_name = source_name

            zip_path = f"{folder}/{dest_name}"

            if isinstance(content, bytes):
                zf.writestr(zip_path, content)
            else:
                zf.writestr(zip_path, str(content).encode("utf-8"))

        # Add collaboration appendix if provided
        if collaboration_appendix:
            zf.writestr(
                "05_Evidence_Appendix/Collaboration_Notes.txt",
                collaboration_appendix,
            )

    buf.seek(0)
    return buf.getvalue()
