"""
PipelineOrchestrator — class-based wrapper around run_analysis_pipeline().

Provides a clean object-oriented API for running the analysis pipeline
while preserving full backward compatibility with the existing function.

Usage:
    from src.analysis.pipeline_orchestrator import PipelineOrchestrator

    orch = PipelineOrchestrator(
        project_id="proj_123",
        output_dir=Path("/tmp/out"),
        run_mode="standard_review",
        tenant_id="acme",
    )
    result = orch.run(input_files=[Path("tender.pdf")])
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Callable, Dict, Any, List, Optional

logger = logging.getLogger(__name__)


class PipelineOrchestrator:
    """
    Stateful orchestrator for the xBOQ analysis pipeline.

    Wraps ``run_analysis_pipeline()`` with per-instance configuration,
    stage tracking, and optional Supabase project persistence.

    Parameters
    ----------
    project_id:
        Unique project identifier (generated by ``generate_project_id()``
        if not provided).
    output_dir:
        Directory where pipeline artifacts are written.
    run_mode:
        Pipeline depth — ``demo_fast`` | ``standard_review`` | ``full_audit``.
    llm_client:
        Optional Anthropic/OpenAI client for LLM-enriched analysis.
    tenant_id:
        Supabase org_id for persisting results.  If *None* and Supabase is
        configured, results are saved anonymously.
    progress_callback:
        ``(stage_id, message, pct)`` callable for real-time progress updates.
    """

    def __init__(
        self,
        project_id: Optional[str] = None,
        output_dir: Optional[Path] = None,
        run_mode: str = "demo_fast",
        llm_client=None,
        tenant_id: Optional[str] = None,
        progress_callback: Optional[Callable[[str, str, float], None]] = None,
    ) -> None:
        from .pipeline import generate_project_id

        self.project_id = project_id or generate_project_id()
        self.output_dir = output_dir or Path("/tmp/xboq") / self.project_id
        self.run_mode = run_mode
        self.llm_client = llm_client
        self.tenant_id = tenant_id
        self.progress_callback = progress_callback

        self._last_result = None  # AnalysisResult from most recent run()

    # ── Properties ───────────────────────────────────────────────────────────

    @property
    def last_result(self):
        """Return the AnalysisResult from the most recent ``run()`` call."""
        return self._last_result

    @property
    def payload(self) -> Dict[str, Any]:
        """Return the payload dict from the last run, or empty dict."""
        if self._last_result and self._last_result.success:
            return self._last_result.payload or {}
        return {}

    @property
    def success(self) -> bool:
        """Return True if the last run completed successfully."""
        return bool(self._last_result and self._last_result.success)

    @property
    def stage_summary(self) -> List[Dict[str, Any]]:
        """Return a list of stage dicts from the last run."""
        if not self._last_result:
            return []
        return [
            {
                "id": s.id,
                "name": s.name,
                "status": s.status,
                "message": s.message,
                "progress": s.progress,
            }
            for s in (self._last_result.stages or [])
        ]

    # ── Core ─────────────────────────────────────────────────────────────────

    def run(
        self,
        input_files: List[Path],
        boq_excel_paths: Optional[List[Path]] = None,
    ):
        """
        Execute the full analysis pipeline.

        Parameters
        ----------
        input_files:
            PDF files to analyse.
        boq_excel_paths:
            Optional Excel BOQ files to cross-reference.

        Returns
        -------
        AnalysisResult
        """
        from .pipeline import run_analysis_pipeline

        self.output_dir.mkdir(parents=True, exist_ok=True)

        self._last_result = run_analysis_pipeline(
            input_files=input_files,
            project_id=self.project_id,
            output_dir=self.output_dir,
            progress_callback=self.progress_callback,
            run_mode=self.run_mode,
            boq_excel_paths=boq_excel_paths,
            llm_client=self.llm_client,
            tenant_id=self.tenant_id,
        )

        # Auto-persist to Supabase if configured and run succeeded
        if self._last_result.success and self.tenant_id:
            self._persist_to_supabase()

        return self._last_result

    # ── Supabase persistence ──────────────────────────────────────────────────

    def _persist_to_supabase(self) -> Optional[str]:
        """Save the payload to Supabase projects table. Returns project id or None."""
        try:
            from src.auth.project_store import save_project
            from src.auth.supabase_client import is_configured

            if not is_configured():
                return None

            payload = self._last_result.payload or {}
            summary = {
                "line_items_count": len(payload.get("line_items", [])),
                "rfi_count": len(payload.get("rfis", [])),
                "boq_items_count": len(payload.get("boq_items", [])),
                "qa_score": payload.get("qa_score", {}).get("total_score"),
                "duration_sec": self._last_result.duration_sec,
            }

            saved_id = save_project(
                org_id=self.tenant_id,
                user_id=self.tenant_id,  # fallback: use org_id as user_id
                filename=str(self.project_id),
                summary=summary,
                payload=payload,
            )
            logger.info("Persisted to Supabase: %s", saved_id)
            return saved_id

        except Exception as exc:
            logger.warning("Supabase persistence skipped: %s", exc)
            return None

    # ── Convenience ──────────────────────────────────────────────────────────

    def export_excel(self, output_path: Optional[Path] = None) -> Optional[Path]:
        """Generate Excel BOQ export. Returns path or None on failure."""
        if not self.success:
            return None
        output_path = output_path or self.output_dir / "boq.xlsx"
        try:
            from src.export import export_boq_excel
            export_boq_excel(self.payload, output_path)
            return output_path if output_path.exists() else None
        except Exception as exc:
            logger.warning("Excel export failed: %s", exc)
            return None

    def export_pdf_summary(self, output_path: Optional[Path] = None) -> Optional[Path]:
        """Generate PDF summary. Returns path or None on failure."""
        if not self.success:
            return None
        output_path = output_path or self.output_dir / "summary.pdf"
        try:
            from src.export import export_pdf_summary
            export_pdf_summary(self.payload, output_path)
            return output_path if output_path.exists() else None
        except Exception as exc:
            logger.warning("PDF export failed: %s", exc)
            return None

    def export_rfi_word(self, output_path: Optional[Path] = None) -> Optional[Path]:
        """Generate Word RFI document. Returns path or None on failure."""
        if not self.success:
            return None
        output_path = output_path or self.output_dir / "rfis.docx"
        try:
            from src.export import export_rfi_word
            export_rfi_word(self.payload, output_path)
            return output_path if output_path.exists() else None
        except Exception as exc:
            logger.warning("Word export failed: %s", exc)
            return None

    # ── Repr ─────────────────────────────────────────────────────────────────

    def __repr__(self) -> str:
        status = "success" if self.success else ("pending" if not self._last_result else "failed")
        return (
            f"PipelineOrchestrator("
            f"project_id={self.project_id!r}, "
            f"run_mode={self.run_mode!r}, "
            f"status={status!r})"
        )
